[server]
port = 10000
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"

[browser]
gatherUsageStats = false
serverAddress = "real-time-stock-market-data-analysis.onrender.com"
